### ISSUE TITLE
How to use HawkTracer without an OS

### ISSUE THREAD

**Issue by andreasbuhr** [amzn/hawktracer#73]
I would like to use HawkTracer without an operating system, so without any threads. I am targeting an ARM Cortex-M7 microcontroller. At the moment, there is always some way of threading necessary. It would be great if it was possible to configure some build configuration variable like "HT_NO_THREADING" or similar to remove all threading related parts from the library.

**Comment by loganek** [comment]
@andreasbuhr thank you for the request. I considered this feature a while ago, but due to lack of time and no real usecase I decided to postpone it. I'll put some priority on that feature and try work on that in the upcoming weeks, will keep you updated here.

Just for you to know, I'm going to only disable threading optionally, but HawkTracer will still require libc to build. Dropping libc dependency is a bit of extra work, and I'm not sure if that's really needed for your usecase - if it is, please let me know, we can consider that as well for the future (but I'd keep this issue just for no-thread option).

Btw I recently found my ATmega so I think I'll be able to actually test the feature on real device :)

**Comment by andreasbuhr** [comment]
That's great to hear, thank you so much. Would be great to see HawkTracer running on an ATmega. Let me know if I can be of any help.

**Comment by loganek** [comment]
@andreasbuhr I've pushed changes to `mkolny/optional-threads` branch. To configure the project, run:
```
$ cmake -DENABLE_THREADS=OFF -DENABLE_TCP_LISTENER=OFF <build dir>
```
Optionally you can disable client (`-DENABLE_CLIENT=OFF`) and tests (`-DENABLE_TESTS=OFF`) as I assume you build it with your custom toolchain (`-DCMAKE_TOOLCHAIN_FILE`).

If you use amalgamated file (hawktracer.c or hawktracer.cpp) you need make sure the `HT_ENABLE_THREADS` and `HT_USE_PTHREADS` is **NOT** defined in `ht_config.h` file.

For AVR, I also had to provide custom monotonic clock implementation. In that case, you define `HT_MONOTONIC_CLOCK_IMPL_CUSTOM` and implement `HT_TimestampNs ht_monotonic_clock_get_timestamp(void)` function somewhere in your code.

The whole threading thing is not documented yet, however, I think it's in a good shape for testing - I'd be very grateful if you could checkout the branch and try to compile it with your project.

Many thanks!

**Comment by andreasbuhr** [comment]
Hi Marcin, wow, that's great! Thank you so much. I just tried compiling the code in https://ide.mbed.com, there are a few issues remaining. If you want me to I could have a look at these next weekend.

The errors I encountered (line numbers might be slightly off)
Error: Identifier "SIZE_MAX" is undefined in "hawktracer.cpp", Line: 1782, Col: 68
Error: Identifier "INT32_MAX" is undefined in "hawktracer.cpp", Line: 3269, Col: 42
Error: Thread-local variable cannot be dynamically initialized in "main.cpp", Line: 32, Col: 10

The third error has to do with the definition of  HT_THREAD_LOCAL. Defining it as empty fixes the problem.

**Comment by loganek** [comment]
@andreasbuhr Thank you for testing it. The first two issues are general problems, not related to threading itself - we've missed including a `stdint.h` file where those two macros are defined (and it's OK to include them, as they're part of c99 standard which is the minimum HawkTracer requirement).

The `HT_THREAD_LOCAL` one was my miss when implementing the support for optional threading - it's definitely not needed to have the macro defined, so I define it to empty if threading is disabled. I pushed all the changes to the same branch, so I'd be grateful if you could test it one more time (I've tested it as well on mbed, but it passed the compilation even without any changes - I guess it depends on the library/platform you choose for compilation?).

**Comment by andreasbuhr** [comment]
Hi, thanks for your work. I tested it again and the errors about SIZE_MAX not being defined persist. Including stdint.h or cstdint does not help. I think it is a problem with the ide.mbed.com toolchain. I opened a thread in their forum to ask for help:
https://forums.mbed.com/t/size-max-not-defined-when-using-online-compiler/8173
I'll keep this issue here updated.

**Comment by loganek** [comment]
Thanks for the update. Looks like the thread is silent for now - if you don't get any response within a week, I think we could also workaround it in HawkTracer (I don't think `SIZE_MAX` is actually needed, and `INT32_MAX` can easily be defined as it's platform-independent constant).

**Comment by loganek** [comment]
I didn't see any response on the mbed thread, so I've predefined the problematic constants in HawkTracer. @andreasbuhr could you please test the branch one more time with the recent changes?
Many thanks!

**Comment by andreasbuhr** [comment]
Great, thanks a lot for your effort.
It works now. 

What I did:
I configured with
```cmake -DENABLE_THREADS=OFF -DENABLE_TCP_LISTENER=OFF -DENABLE_CLIENT=OFF -DENABLE_TESTS=OFF```
then copied the amalgamated h/cpp files to the project, uncommented ```#define HT_MONOTONIC_CLOCK_IMPL_CUSTOM``` in ht_config.h.
Then I implemented ht_monotonic_clock_get_timestamp.

Great!

**Comment by loganek** [comment]
The change has been merged. Thank you @andreasbuhr for help with testing! Feel free to re-open the issue or open a new one if you experience any problems with that feature.
